### ISSUE TITLE
Ownership of nrf51::Peripherals

### ISSUE THREAD

**Issue by wendeldr** [therealprof/nrf51#1] opened 2018-03-08 02:45 UTC
@therealprof I am having some trouble utilizing 2 of your libraries, nrf51, nrf51-hal.  I am working off a nrf51-dk board and trying to implement some of the examples from your microbit repo for the nrf51.  I've gotten your gpio_hal_blinky.rs running fine and  modified your gpio_hal_printbuttons.rs to work as follows (although its extremely slow to respond and I'm not sure whats causing that) 
```
#![feature(used)]
#![feature(const_fn)]
#![feature(use_extern_macros)]
#![no_std]

extern crate cortex_m;
extern crate nrf51;
extern crate nrf51_hal;
extern crate cortex_m_semihosting;

use nrf51_hal::prelude::*;

use cortex_m::peripheral::Peripherals;
use cortex_m::interrupt::Mutex;
use cortex_m_semihosting::hio;

use core::cell::RefCell;
use core::fmt::Write;

static GPIO: Mutex<RefCell<Option<nrf51::GPIOTE>>> = Mutex::new(RefCell::new(None));

fn main() {
    if let (Some(p), Some(mut cp)) = (nrf51::Peripherals::take(), Peripherals::take()) {
        cortex_m::interrupt::free(move |cs| {
            let mut stdout = hio::hstdout().unwrap();
            /* Enable external GPIO interrupts */
            cp.NVIC.enable(nrf51::Interrupt::GPIOTE);
            cp.NVIC.clear_pending(nrf51::Interrupt::GPIOTE);

            /* Split GPIO pins */
            let gpio = p.GPIO.split();

            /* Configure button GPIOs as inputs */
            let _ = gpio.pin17.into_floating_input();

            /* Set up GPIO 17 (button A) to generate an interrupt when pulled down */
            p.GPIOTE.config[0]
                .write(|w| unsafe { w.mode().event().psel().bits(17).polarity().hi_to_lo() });
            p.GPIOTE.intenset.write(|w| w.in0().set_bit());
            p.GPIOTE.events_in[0].write(|w| unsafe { w.bits(0) });

            *GPIO.borrow(cs).borrow_mut() = Some(p.GPIOTE);

            writeln!(stdout, "Main ran").unwrap();
        });
    }
}

/* Define an exception, i.e. function to call when exception occurs. Here if we receive an
 * interrupt from a button press, the printbuttons function will be called */
nrf51::interrupt!(GPIOTE, printbuttons);

fn printbuttons() {
    /* Enter critical section */
    cortex_m::interrupt::free(|cs| {
        if let Some(gpiote) = GPIO.borrow(cs).borrow().as_ref() {
            let mut stdout = hio::hstdout().unwrap();
            writeln!(stdout, "A Button was Pressed").unwrap();

            /* Clear events */
            gpiote.events_in[0].write(|w| unsafe { w.bits(0) });
        }
    });
}
```

I am now trying to combine the two and cause the lights to turn on when a button is pressed but I'm struggling.  I cannot figure out how to get access to the nrf51::Peripherals within the printbuttons function without causing ownership errors.  Do you have any recommendations or insights into how I can do this?  Sorry if this is a trivial question I'm new to Rust and embedded programming.

**Comment by therealprof** [comment] 2018-03-08 10:15
No idea what causes your slowness, could be the semihosting output which is **really** slow. 
In order to allow the interrupt handler to access the LED you'll need to setup the LED pin as in the `gpio_hal_blinky` example, define a static LED `Mutex<RefCell<...>>` thingymabob as in the example you cited above and assign it the led pin and then access it from the interrupt handler. The implementation should be pretty similar to the `gpio_hal_printbuttons` example but with the serial setup and output substituted by a GPIO setup and toggle.

**Comment by Flickdm** [comment] 2018-03-20 00:18
The issue isn't a matter of "Slowness" but rather the interrupt is being hit intermittently due to a floating ground. The microbit is designed to work with floating input whereas the nrf51dk needs a pull up.

So the proper way to handle the interrupt is to set
```rust
 let _ = gpio.pin17.into_floating_input();
```
to
```rust
let _ = gpio.pin17.into_pull_up_input();
```

and then set the interrupt event to occur on a pull up from lo_to_hi
```rust
p.GPIOTE.config[0].write(|w| unsafe { w.mode().event().psel().bits(17).polarity().hi_to_lo()});
```
to 
```rust
p.GPIOTE.config[0].write(|w| unsafe { w.mode().event().psel().bits(17).polarity().lo_to_hi()});
```

**Closed as completed** 2018-03-20 00:23 UTC
